export const metadata = {
  title: "about",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
        <>
        <div className="text-white">
        <span>About</span>
        {children}
        </div>
        </>
  );
}