export const metadata = {
    title: "admin logout",
    description: "Generated by create next app",
  };
  
export default function AdminlogoutLayout({ children }) {
    return (
        <>
        <div>Admin logout navbar</div>
          {children}
        </>
    );
  }